version: '3.8'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: 'redis/redis-stack-server:latest'
    ports:
      - '6379:6379'
